// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var searchSong, socket;
    socket = io.connect('http://127.0.0.1:6969');
    socket.on('welcome', function(data) {
      return console.log(data);
    });
    socket.on('download-error', function(err) {
      return alert('Error when download file. Please try again later!');
    });
    socket.on('download-done', function(info) {
      var songDetail;
      songDetail = "<li data-client='" + info.ip + "'>\n    " + info.name + "\n    <span>" + info.artist + "</span>\n</li>";
      $(songDetail).hide().appendTo('#playlist ul').slideDown(1000);
      return $('#accept-btn').text('Accept').prop('disabled', false);
    });
    $('#search').on('click', function() {
      searchSong();
      return false;
    });
    $('#song-name').on('keypress', function(e) {
      if (e.keyCode === 13) {
        return searchSong();
      }
    });
    $('#song-name').on('click focus', function() {
      return $(this).select();
    });
    $(document).on('click', '.song-item', function() {
      var $item, itemUrl, yqlStatement;
      $item = $(this);
      itemUrl = $item.prop('href');
      yqlStatement = "SELECT * FROM html WHERE url='" + itemUrl + "' AND xpath='//div[@class=\"download\"]//a'";
      $.queryYQL(yqlStatement, function(data) {
        if (data.query.count === 1) {
          $('#player').html("<audio autoplay repeat controls><source src='" + data.query.results.a.href + "' type='audio/mpeg' /></audio>");
          $item.closest('#results').find('p').removeClass('playing');
          return $item.parent().addClass('playing');
        } else {
          return alert('Error. Please try again later');
        }
      });
      return false;
    });
    $('#accept-btn').on('click', function() {
      var songArtist, songName, songUrl;
      songUrl = $("#player audio source").prop('src');
      songName = $('.playing a').text();
      songArtist = $('.playing span').text();
      if (songUrl && songUrl !== '') {
        socket.emit('download-song', {
          url: songUrl,
          name: songName,
          artist: songArtist
        });
        return $(this).text('Downloading...').prop("disabled", true);
      } else {
        return alert('Please select a song to download it.');
      }
    });
    return searchSong = function() {
      var searchUrl, songName, yqlStatement;
      songName = encodeURIComponent($('#song-name').val().trim());
      searchUrl = 'http://m.nhaccuatui.com/tim-kiem?q=';
      if (songName !== '') {
        yqlStatement = "SELECT * FROM html WHERE url='" + (searchUrl + songName) + "' AND xpath='//div[@class=\"row bgmusic\"]'";
        $('#results').html('Loading. Please wait...');
        return $.queryYQL(yqlStatement, function(data) {
          $('#results').empty();
          return $.each(data.query.results.div, function(index, item) {
            return $('#results').append("<p><a class='song-item' href='" + item.h3.a.href + "'>" + item.h3.a.content + "</a><span>" + item.p.content + "</span></p>");
          });
        });
      } else {
        return $('#song-name').focus();
      }
    };
  });

}).call(this);
